const tl = gsap.timeline({ repeat: -1, repeatDelay: 1 });

tl.to('.button.no1', { scale: 1, opacity: 1, delay: 0.5, duration: 0.5 });
tl.to('.button.no1', { scale: 0.9, duration: 0.25 });
tl.to('.button.no1', { scale: 1, duration: 0.25 });
tl.to('.button.no1', { opacity: 0, delay: 0.5, duration: 0.5 });
tl.to('.button.no1', { duration: 0, text: 'Push' });
tl.to('.animation.no1', { opacity: 1, delay: -0.5, duration: 0.25 });
tl.to('.animation.no1', { scale: 1.2, duration: 0.2 });
tl.to('.animation.no1', { scale: 1, duration: 0.2 });
tl.to('.animation.no1', { scale: 1.2, duration: 0.2 });
tl.to('.animation.no1', { scale: 1, duration: 0.2 });
tl.to('.animation.no1', { opacity: 0, duration: 0.2 });
tl.to('.animation.no1', { text: '📄', duration: 0, ease: 'none' });
tl.to('.button.no1', { scale: 1, opacity: 1, delay: 0.5, duration: 0.5 });
tl.to('.button.no1', { scale: 0.9, duration: 0.25 });
tl.to('.button.no1', { scale: 1, duration: 0.25 });
tl.to('.button.no1', { opacity: 0, delay: 0.5, duration: 0.5 });
tl.to('.animation.no1', { scale: 1, opacity: 1, delay: -0.5, duration: 0.25 });
tl.to('.animation.no1', { x: '250%', y: '-375%', duration: 1.5 });
tl.to('.button.no2', { scale: 1, opacity: 1, duration: 0.25 });
tl.to('.button.no2', { scale: 0.9, duration: 0.25 });
tl.to('.button.no2', { scale: 1, duration: 0.25 });
tl.to('.button.no2', { opacity: 0, delay: 0.5, duration: 0.5 });
tl.to('.button.no2', { duration: 0, text: 'Push' });
tl.to('.animation.no2', { opacity: 1, delay: -0.5, duration: 0.25 });
tl.to('.animation.no2', { scale: 1.2, duration: 0.2 });
tl.to('.animation.no2', { scale: 1, duration: 0.2 });
tl.to('.animation.no2', { scale: 1.2, duration: 0.2 });
tl.to('.animation.no2', { scale: 1, duration: 0.2 });
tl.to('.animation.no2', { opacity: 0, duration: 0.2 });
tl.to('.animation.no2', { text: '📄', duration: 0 });
tl.to('.button.no2', { scale: 1, opacity: 1, delay: 0.5, duration: 0.5 });
tl.to('.button.no2', { scale: 0.9, duration: 0.25 });
tl.to('.button.no2', { scale: 1, duration: 0.25 });
tl.to('.button.no2', { x: '-25%', rotateZ: '-5deg', delay: 0.25, duration: 0.2 });
tl.to('.button.no2', { x: '20%', rotateZ: '3deg', duration: 0.2 });
tl.to('.button.no2', { x: '-15%', rotateZ: '-3deg', duration: 0.2 });
tl.to('.button.no2', { x: '10%', rotateZ: '2deg', duration: 0.2 });
tl.to('.button.no2', { x: '-5%', rotateZ: '-1deg', duration: 0.2 });
tl.to('.button.no2', { x: '0', rotateZ: '0deg', duration: 0.2 });
tl.to('.animation.no2', { opacity: 1, delay: -1.2, duration: 0.25 });
tl.to('.button.no2', { opacity: 0, delay: 0.5, duration: 0.2 });
tl.to('.button.no2', { duration: 0, text: 'Pull' });
tl.to('.mask', { opacity: 0.5, delay: 0.25, duration: 0.5 });
tl.to('.popup', { opacity: 1, scale: 1, delay: -0.25, duration: 0.5 });
tl.to('.popup', { opacity: 0, scale: 0.5, delay: 4, duration: 0.5 });
tl.to('.mask', { opacity: 0, delay: -0.5, duration: 0.5 });
tl.to('.button.no2', { scale: 1, opacity: 1, delay: 0.5, duration: 0.5 });
tl.to('.button.no2', { scale: 0.9, duration: 0.25 });
tl.to('.button.no2', { scale: 1, duration: 0.25 });
tl.to('.animation.no1', { x: '495%', y: '-5%', duration: 1.5 });
tl.to('.button.no2', { opacity: 0, delay: -0.5, duration: 0.2 });
tl.to('.button.no2', { duration: 0, text: 'Push' });
tl.to('.button.no2', { scale: 1, opacity: 1, delay: 0.5, duration: 0.5 });
tl.to('.button.no2', { scale: 0.9, duration: 0.25 });
tl.to('.button.no2', { scale: 1, duration: 0.25 });
tl.to('.button.no2', { opacity: 0, delay: 0.25, duration: 0.2 });
tl.to('.animation.no1', { x: '245%', y: '-380%', duration: 1.5 });
tl.to('.animation.no2', { x: '-250%', y: '-375%', delay: -1.5, duration: 1.5 });
tl.to('.animation.no1', { opacity: 0, delay: 1, duration: 0.25 });
tl.to('.animation.no2', { opacity: 0, delay: -0.25, duration: 0.25 });